// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R_gig.cpp
cpp11::writable::doubles sample_gig_cpp(int n, double p, double a, double b);
extern "C" SEXP _customdists_sample_gig_cpp(SEXP n, SEXP p, SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(sample_gig_cpp(cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<double>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_customdists_sample_gig_cpp", (DL_FUNC) &_customdists_sample_gig_cpp, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_customdists(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
